# Generated by Django 6.1 on 2026-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('maintainers', models.JSONField(blank=True, default=list, help_text='Enter one maintainer per line using the format: Name, email address.')),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('mcp_server', 'MCP Server'), ('agent', 'Agent'), ('skills_md', 'Skills.md')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Example: ['simulation', 'geometry']")),
                ('logo_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('internal_url', models.URLField(blank=True, help_text='Example: [{"name": "run_simulation", "description": "Runs a simulation"}]')),
                ('external_url', models.URLField(blank=True)),
                ('tools', models.JSONField(blank=True, default=list, help_text='Example: [{"name": "run_simulation", "description": "Runs a simulation"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
