# Generated by Django 6.1 on 2026-09-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='from_official_team',
            field=models.BooleanField(default=False),
        ),
    ]
