# Generated by Django 6.1 on 2026-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cards_from_official_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='internal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='maintainers',
            field=models.JSONField(blank=True, default=list, help_text='Example (be sure to use double quotes ""): [{"name": "First Maintainer", "email": "1st@fake.com"}, {"name": "Second Maintainer", "email": "2nd@fake.com"}]'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Example (be sure to use double quotes ""): ["simulation", "geometry"]'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='tools',
            field=models.JSONField(blank=True, default=list, help_text='Example (be sure to use double quotes ""): [{"name": "run_simulation", "description": "Runs a simulation"}, {"name": "post_process", "description": "Post-processes simulation results"}]'),
        ),
    ]
